/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
    './error.vue',
  ],
  theme: {
    extend: {},
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        ocnlight: {
          primary: '#3B82F6',
          'primary-content': '#ffffff',
          secondary: '#10B981',
          'secondary-content': '#ffffff',
          accent: '#F59E0B',
          'accent-content': '#000000',
          neutral: '#374151',
          'neutral-content': '#ffffff',
          'base-100': '#FFFFFF',
          'base-200': '#F3F4F6',
          'base-300': '#E5E7EB',
          'base-content': '#1F2937',
          info: '#06B6D4',
          'info-content': '#ffffff',
          success: '#10B981',
          'success-content': '#ffffff',
          warning: '#F59E0B',
          'warning-content': '#000000',
          error: '#EF4444',
          'error-content': '#ffffff',
        },
        ocndark: {
          primary: '#60A5FA',
          'primary-content': '#000000',
          secondary: '#34D399',
          'secondary-content': '#000000',
          accent: '#FBBF24',
          'accent-content': '#000000',
          neutral: '#1F2937',
          'neutral-content': '#ffffff',
          'base-100': '#111827',
          'base-200': '#1F2937',
          'base-300': '#374151',
          'base-content': '#F9FAFB',
          info: '#22D3EE',
          'info-content': '#000000',
          success: '#34D399',
          'success-content': '#000000',
          warning: '#FBBF24',
          'warning-content': '#000000',
          error: '#F87171',
          'error-content': '#000000',
        },
      },
      'light',
      'dark',
      'cupcake',
      'business',
    ],
    darkTheme: 'ocndark',
    base: true,
    styled: true,
    utils: true,
  },
}
